---
FRIGATE_MQTT_HOST: !secret SECRET_FRIGATE_MQTT_HOST
FRIGATE_MQTT_USERNAME: !secret SECRET_FRIGATE_MQTT_USERNAME
FRIGATE_MQTT_PASSWORD: !secret SECRET_FRIGATE_MQTT_PASSWORD
FRIGATE_CAMERA1_WEBUI_URL: !secret SECRET_FRIGATE_CAMERA1_WEBUI_URL
FRIGATE_CAMERA1_PATH: !secret SECRET_FRIGATE_CAMERA1_PATH
