---
default_config:
mobile_app:

homeassistant:
  name: Home
  legacy_templates: false

  time_zone: Europe/Amsterdam
  latitude: !secret SECRET_HOME_LATITUDE
  longitude: !secret SECRET_HOME_LONGITUDE
  elevation: !secret SECRET_HOME_ELEVATION

  unit_system: metric
  temperature_unit: C
  currency: EUR

  # external_url: !secret SECRET_HASS_EXTERNAL_URL
  # internal_url: !secret SECRET_HASS_INTERNAL_URL

  # Load packages
  packages: !include_dir_named packages

  media_dirs:
    local: /media

  allowlist_external_dirs: /

# Integrations
automation: !include_dir_list ./automations/
device_tracker: !include_dir_list ./integrations/device_tracker/
http: !include ./integrations/http.yaml
# influxdb: !include ./integrations/influxdb.yaml
lovelace: !include ./integrations/lovelace.yaml
prometheus: !include ./integrations/prometheus.yaml
recorder: !include ./integrations/recorder.yaml
script: !include_dir_merge_named ./scripts/
# telegram_bot: !include ./integrations/telegram_bot.yaml
utility_meter: !include ./entities/utility_meter.yaml
webhook:
notify: !include_dir_list ./integrations/notify/
rest_command: !include_dir_merge_named ./integrations/rest_commands/

# webhook: !include integrations/webhooks.yaml

# Entities
# fan: !include_dir_list ./entities/fans/
input_number: !include_dir_merge_named ./entities/input_numbers/
# media_player: !include_dir_list ./entities/media_players/
sensor: !include_dir_list ./entities/sensors/
switch: !include_dir_list ./entities/switches/
zone: !include_dir_list ./entities/zones/

panel_iframe:
  networkmap:
    title: 'Zigbee Map'
    url: '/local/community/zigbee2mqtt_networkmap/map.html'
    icon: 'mdi:graphql'

