---
id: "office_zone_movement"
alias: Office - Zone movement
description: ""
trigger:
  - platform: zone
    entity_id:
      - person.jorn_eilander
      - person.maeike_eilander
    zone: zone.ing_acanthus
    event: enter
  - platform: zone
    entity_id:
      - person.jorn_eilander
      - person.maeike_eilander
    zone: zone.ing_acanthus
    event: leave
action:
  - service: notify.all_devices
    data:
      message: |
        {% if trigger.event == "leave" %}
          {{ trigger.from_state.attributes.friendly_name }} left zone: {{ trigger.zone.attributes.friendly_name }}
        {% else %}
          {{ trigger.from_state.attributes.friendly_name }} entered zone: {{ trigger.zone.attributes.friendly_name }}
        {% endif %}
      data:
        sticky: true
