---
alias: Attick Light - On on motion
id: "attick_light_on_when_motion"
description: ""
trigger:
  - platform: state
    entity_id: binary_sensor.attick_landing_motion_detector_occupancy
    to: "on"
condition: []
action:
  - service: light.turn_on
    target:
      entity_id: light.attick_landing_light
    data:
      brightness_pct: |
        {%- if (now() > today_at("19:30")) or (now() < today_at("07:30")) -%}
        1
        {%- else -%}
        100
        {%- endif -%}
      transition: 2
mode: restart
