---
alias: Attick Light - On on motion
id: "attick_light_on_when_motion"
description: ""
trigger:
  - platform: state
    entity_id: binary_sensor.attick_landing_motion_detector_occupancy
    to: "on"
condition: []
action:
  - service: light.turn_on
    target:
      entity_id: light.attick_landing_light
    data:
      brightness_pct: 25
mode: restart
