---
alias: Living room - Turn on lights when door opened before 09:00
id: "living_room_lights_on_when_door_opened_before_nine"
description: "Turn on lights when door opened before 09:00"
trigger:
  - platform: state
    entity_id: binary_sensor.living_room_door_sensor_contact
    from: "off"
    to: "on"
condition:
  - condition: and
    conditions:
      # - alias: "Before 09:00"
      #   condition: time
      #   before: "09:00:00"
      - alias: "Dark room"
        condition: numeric_state
        entity_id: sensor.living_room_motion_detector_illuminance_lux
        below: 30
action:
  - service: light.turn_on
    data:
      brightness_pct: 100
    entity_id: light.dining_room_lights
  - service: light.turn_on
    data:
      brightness_pct: 100
    entity_id: light.living_room_lights
mode: single
