---
alias: Living room - Lights on when door opened
id: "living_room_lights_on_when_door_opened"
description: "Turn on lights when door is opened"
trigger:
  - platform: state
    entity_id: binary_sensor.living_room_door_sensor_contact
    from: "off"
    to: "on"
condition: []
action:
  - service: light.turn_on
    data:
      brightness_pct: 100
    entity_id: light.dining_room_lights
  - service: light.turn_on
    data:
      brightness_pct: |-
        {%- if (states('sensor.living_room_motion_detector_illuminance_lux') | int ) < (states('input_number.living_room_light_trigger_lux') | int) -%}
        100
        {%- else -%}
        0
        {%- endif -%}
    entity_id: light.living_room_lights
mode: single
