---
alias: Hallway light - On on motion
id: "hallway_light_on_when_motion"
description: ""
trigger:
  - platform: state
    entity_id: binary_sensor.hallway_motion_detector_occupancy
    to: "on"
condition: []
action:
  - service: light.turn_on
    target:
      entity_id: light.hallway_light
    data:
      brightness_pct: |
        {%- if (now() > today_at("19:30")) or (now() < today_at("09:00")) -%}
        1
        {%- elif (states('sensor.hallway_motion_detector_illuminance_lux') | default(0) | int ) <  ( states('input_number.hallway_light_trigger_lux') | int ) -%}
        50
        {%- else -%}
        0
        {%- endif -%}
      transition: 2
mode: restart
