---
id: notify_when_front_door_opened
alias: Hallway - Notify when front door opened
trigger:
  - platform: state
    entity_id: binary_sensor.hallway_door_sensor_contact
    from: "off"
    to: "on"
action:
  # - alias: "Front door opened notice"
  #   service: notify.mobile_app_geironul
  #   data:
  #     message: "Front door has been opened"
  #     data:
  #       sticky: false
  - alias: "Turn on hallway light"
    service: light.turn_on
    data:
        brightness_pct: 40
    target:
      entity_id: light.hallway_light
