---
alias: "Mindergas.nl - Post meter readings"
triggers:
  - trigger: time
    at: "00:02:03"
actions:
  - action: rest_command.mindergas_post_meter_readings
    data_template:
      ## use 1h before now, to make sure we use yesterdays date
      date: "{{ (now() - timedelta(hours = 1)).date() }}"
      meter_reading: "{{ states('sensor.dsmr_reader_gas_delivered') }}"
