---
alias: 🔥 Smoke Alarm 🔥
id: "smoke_sensor_triggered"
mode: restart
trigger:
  - platform: event
    event_type: state_changed
condition:
  - condition: template
    value_template: "{{ trigger.event.data.new_state is not none }}"
  - condition: template
    value_template: "{{ trigger.event.data.new_state.attributes is not none }}"
  - condition: template
    value_template:
      "{{ trigger.event.data.new_state.attributes.device_class == 'smoke' }}"
  - condition: template
    value_template: "{{ trigger.event.data.new_state.state == 'on' }}"
action:
  - service: telegram_bot.send_message
    data:
      message: '🔥 Smoke Alarm 🔥

        {{ trigger.event.data.new_state.attributes.friendly_name | replace(''_'',''\_'') }}
        has changed state to: {{ trigger.event.data.new_state.state }}'
  - service: notify.all_devices
    data:
      message: '🔥 Smoke Alarm 🔥

        {{ trigger.event.data.new_state.attributes.friendly_name | replace(''_'',''\_'') }}
        has changed state to: {{ trigger.event.data.new_state.state }}'
      data:
        sticky: true
