---
alias: Doorbell - Notification when pressed
id: "notification_when_doorbell_press"
description: ""
mode: single
trigger:
  - alias: Someone presses the doorbell
    trigger: state
    entity_id: binary_sensor.doorbell_visitor
    to: "on"
condition: []
variables:
  local_time: "{{ now().strftime('%Y-%m-%dT%H%M%S%Z') }}"
  snapshot_path_local: "/config/www/tmp/{{ local_time }}.jpg"
  snapshot_path_external: "/local/tmp/{{ local_time }}.jpg"
actions:
  - alias: "Send an alert to everyone"
    action: notify.mobile_jorn_maeike_priority_high
    data:
      message: |
        There is someone at the door!
  - alias: Take a snapshot
    action: camera.snapshot
    data:
      filename: "{{ snapshot_path_local }}"
    target:
      entity_id: camera.doorbell_clear
  - delay: '00:00:02'
  - alias: Send the snapshot to everyone
    action: notify.mobile_jorn_maeike_priority_high
    data:
      message: Here they are
      data:
        attachment:
          url: "{{ snapshot_path_external }}"
          content_type: "JPEG"
  - alias: Set persistent notification
    action: persistent_notification.create
    data:
      title: Someone was at the door
      message: |
        ![image info]({{ snapshot_path_external }})
